# Static Analyzer Options
#
# For additional info see: https://dart.dev/guides/language/analysis-options
#

include: package:flutter_lints_plus/flutter.yaml

analyzer:
  errors:
    # Treat missing required parameters as an error.
    missing_required_param: error

    # Treat missing returns as an error, not as a hint or a warning.
    missing_return: error
    
    # Allow having TODOs in the code.
    todo: info

  exclude:
    - "bin/cache/**"
    - "test/.test_coverage.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

# Linter rules (see: http://dart-lang.github.io/linter/lints/)
linter:
  rules:
