# Static Analyzer Options
#
# For additional info see: https://dart.dev/guides/language/analysis-options
#

include: package:flutter_lints_plus/flutter.yaml

# Linter rules (see: http://dart-lang.github.io/linter/lints/)
linter:
  rules:
