name: float_column
description: Flutter FloatColumn widget for building a vertical column of widgets and text where the text wraps around floated widgets, similar to how CSS float works.
version: 1.3.1
repository: https://github.com/ronjb/float_column

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints_plus: ^2.0.1
  flutter_test:
    sdk: flutter
