name: float_column
description: A vertical column of widgets and text that supports floating widgets to the left and/or right.
version: 0.0.1
repository: https://github.com/ronjb/flex_text

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
