name: float_column
description: A vertical column of widgets and text with the ability to "float" child widgets to the left or right, allowing the text to wrap around them.
version: 0.0.1
repository: https://github.com/ronjb/float_column

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
